
% MIBIextractRawImages.m
% 
% This script allows you to move from a tof spectra file (.msdf), generated by the MIBI to an N-dimensional image. It performs the following steps:
% A.	Spectra calibration
% B.	Cross correlation and summation of depths
% C.	Generation of QC plots
% To run the script you need to adjust the parameters to match your data. The default parameters in the repository are set for the analysis of the sample data provided in the directory ‘SampleData-Moly’. You should first try to analyze this data to make sure that you can do this correctly, before moving on to your own data.
% •	fileNameXML – the file name of the run xml.
% •	fileNameMass – the file name for the csv file of your panel.
% •	dataDir – the directory of the raw data.
% •	processedDataDir – the directory to which the processed data will be written
% •	pointNumber – the number of the point that is being analyzed.
% •	depthStart and depthEnd – the depths that you want to extract. For a run with only a single depth, both variables should equal 1.
% •	calibrateSpectra – a boolean (1 or zero), indicating whether you want to calibrate the spectra for this run. If you want to use the parameters from the instrument set this to zero. Otherwise, if you suspect that the spectra needs to be calibrated, set this to 1.
% •	First – a boolean indicating whether this is the first run of the script. This is only important if you want to calibrate the spectra. If you want to calibrate the spectra, the scrip will behave differently if this is the first time that you run it or not (see below).
% •	SpectraVec – values used for spectra calibration (see below).
% 
% Spectra calibration
% Data comes off the instrument as time of flight. We want to convert it to mass. There is a quadratic equation relating the two, whose parameters, a and b, can change according to the tuning settings. To calibrate the spectra, we need to indicate two points for which we know the time and the mass, and then the script can solve and find the parameters. We typically use Na and Au, as these elements are at the two edges of the acquired spectrum and are usually highly abundant and easily identifiable in our sample. We know the mass of Na (22.93)  and Au (196.96). To see what was the time of flight of these elements in the current run, we need to see the run spectrum. To this end, we run the script MIBIextractRawImages.m with the parameter First=1. This should plot (Figure 1) the spectrum, summed over the entire image as such:
% 
% Zooming-in on this image, we can see that the time of flight for Na in this run was 3300 and for Au was 9042.
% To use these values for calibration we go back to the script and insert them into the SpectraVec variable as such: SpectraVec = [3300, 22.93, 9042, 196.96]. This tells the script to find parameters such that a TOF of 3300 will be converted to a mass of 22.93, and a TOF of 9042 will be converted to 196.96.
% The script also plots the spectrum as a function of mass, after calibration. So, if we now run with
% calibrateSpectra=1;
% First=1;
% spectraVec=[3300, 22.93, 9042, 196.96];
% you should see the image for the TOF, as well as the  following image of counts per mass:
% 
% This image should make sense. You should see peaks for natural elements (such as Na and Ca) in their expected masses. You should see a relatively large peak for your nuclear marker (e.g. dsDNA on 89 in this case), and additional peaks on the elements that you included in your panel (e.g. 113,115,141-176 in this example.
% 
% Use this plot to double check the values that you set on your integration windows in the .csv file. Once you see how the data looks like, you may want to slightly change these.
% 
% Now that you are sure of your spectra calibration and integration windows, you can rerun the script with First = 0. This will extract the images. Beware, this script may take a few minutes to run, depending on the size of your data and strength of your computer.
% 
% The output for the script is:
% 1.	Folder of TIF images
% 2.	Results folder with figures of quality controls
% 3.	data.mat – a matlab file with the data. It contains:
% a.	massDS – a table with the information from the CSV
% b.	countsAllSFiltCRSum – a matrix of size [x-dimension,y-dimension,number-of-channels] with all the data
% c.	totalIonFiltSum – image of total ion intensity



fileNameXML='SampleData/SampleData.xml';
fileNameMass='SampleData/SamplePanel.csv';
dataDir='SampleData/';
processedDataDir='SampleData/extracted/';
pointNumber=1;
depthStart=1;
depthEnd=1;
% parameters for spectra calibration (if necessary)
calibrateSpectra=1;
First = 0;
spectraVec=[3300,22.930,9042,196.960];

MibiAnalysis3;
